"""Portable public contract for the General Legal Agent assessment."""

from legal_agent_assessment.contracts import (
    AnswerStatus,
    Citation,
    GeneralLegalAgent,
    GeneralLegalRequest,
    GeneralLegalResponse,
    RetrievalHit,
    RuntimeVersions,
)
from legal_agent_assessment.dataset import (
    CoverageEntry,
    DispositionNote,
    DocumentKind,
    GuideIdentity,
    GuideNumberScheme,
    JudgementIdentity,
    LawLinkage,
    LicenceNote,
    LinkageStrength,
    ReleaseFile,
    ReleaseFileKind,
    ReleaseManifest,
    SourceAdmission,
    SourceProvenance,
    SourceRecord,
    TextExtraction,
    UsageDisposition,
    default_corpus,
)
from legal_agent_assessment.dataset_validation import (
    EvaluationLeakError,
    Finding,
    Severity,
    assert_supplied_by_manifest,
    content_hash,
    errors,
    select_index_inputs,
    summarize,
    validate_release,
)
from legal_agent_assessment.record_selection import (
    default_corpus_sentinel_findings,
    select_records_for_indexing,
)

__all__ = [
    "AnswerStatus",
    "Citation",
    "CoverageEntry",
    "DispositionNote",
    "DocumentKind",
    "EvaluationLeakError",
    "Finding",
    "GeneralLegalAgent",
    "GeneralLegalRequest",
    "GeneralLegalResponse",
    "GuideIdentity",
    "GuideNumberScheme",
    "JudgementIdentity",
    "LawLinkage",
    "LicenceNote",
    "LinkageStrength",
    "ReleaseFile",
    "ReleaseFileKind",
    "ReleaseManifest",
    "RetrievalHit",
    "RuntimeVersions",
    "Severity",
    "SourceAdmission",
    "SourceProvenance",
    "SourceRecord",
    "TextExtraction",
    "UsageDisposition",
    "assert_supplied_by_manifest",
    "content_hash",
    "default_corpus",
    "default_corpus_sentinel_findings",
    "errors",
    "select_index_inputs",
    "select_records_for_indexing",
    "summarize",
    "validate_release",
]
